// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using NFB.Service.Vatsim.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NFB.Service.Vatsim.Migrations
{
    [DbContext(typeof(VatsimDbContext))]
    partial class VatsimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NFB.Service.Vatsim.Entities.PilotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("VatsimId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });
#pragma warning restore 612, 618
        }
    }
}
